//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModularApp.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class API {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal API() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModularApp.Main.Properties.API", typeof(API).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   yR3oG8fAfa99DeQqDIVe~AqfQuTkTfMqdChSoumqFow~ApCNPT9Kt1oz7KGtHfEmfx3O1eLsFSMqtwqqrQk3na7VQHG3HWRxWwsCJhwY8M5F과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_BINGMAP {
            get {
                return ResourceManager.GetString("APIKEY_BINGMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U01TX0FVVEgyMDE3MDQyNzAzMTg1MDIwODY3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_JUSO_1 {
            get {
                return ResourceManager.GetString("APIKEY_JUSO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U01TX0FVVEgyMDE3MDQyNzAzMjIyMTIwODY4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_JUSO_2 {
            get {
                return ResourceManager.GetString("APIKEY_JUSO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U01TX0FVVEgyMDE3MDQyNzAzMjY1MzIwODY5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_JUSO_3 {
            get {
                return ResourceManager.GetString("APIKEY_JUSO_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   U01TX0FVVEgyMDE3MDcwOTIwMDIwMTIyNDkw과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_JUSO_4 {
            get {
                return ResourceManager.GetString("APIKEY_JUSO_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   017431432f15192d1f9e3377da7c2954과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_KAKAO {
            get {
                return ResourceManager.GetString("APIKEY_KAKAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7igNF5yqqotAgGcOBzsQVTZQcvT22fbX0cpGpDofB4pXzWPwiVQAiiJiToTNa2q%2FnfnbeRZGLq%2Fe43QKNn1NYw%3D%3D과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_MOLIT {
            get {
                return ResourceManager.GetString("APIKEY_MOLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VisualRealtor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_NAVER_APPLICATION {
            get {
                return ResourceManager.GetString("APIKEY_NAVER_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nC_bKSEjY99CiqTk28ho과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_NAVER_CLIENTID {
            get {
                return ResourceManager.GetString("APIKEY_NAVER_CLIENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FDAilaSRxu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_NAVER_CLIENTSECRET {
            get {
                return ResourceManager.GetString("APIKEY_NAVER_CLIENTSECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://visualreal.iwinv.net과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_NAVER_WEBURL {
            get {
                return ResourceManager.GetString("APIKEY_NAVER_WEBURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   D23414A4-1543-321B-92E0-6C69AEE213D5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_VWORLD {
            get {
                return ResourceManager.GetString("APIKEY_VWORLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   86d8da4705692679873c9e과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_동명조회 {
            get {
                return ResourceManager.GetString("APIKEY_동명조회", resourceCulture);
            }
        }
        
        /// <summary>
        ///   097531dd3beaf06d9b3fdb과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_리조회 {
            get {
                return ResourceManager.GetString("APIKEY_리조회", resourceCulture);
            }
        }
        
        /// <summary>
        ///   620b359224486096f14ead과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_법정구역도WFS조회 {
            get {
                return ResourceManager.GetString("APIKEY_법정구역도WFS조회", resourceCulture);
            }
        }
        
        /// <summary>
        ///   943b8b5a5575bb98c5c909과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_법정구역도조회 {
            get {
                return ResourceManager.GetString("APIKEY_법정구역도조회", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1e2ebb4af231ff576ae9cb과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_시군구조회 {
            get {
                return ResourceManager.GetString("APIKEY_시군구조회", resourceCulture);
            }
        }
        
        /// <summary>
        ///   b5d86edba47898aa57eb11과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_시도조회 {
            get {
                return ResourceManager.GetString("APIKEY_시도조회", resourceCulture);
            }
        }
        
        /// <summary>
        ///   71d472bfee818dc47e71ba과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string APIKEY_읍면동조회 {
            get {
                return ResourceManager.GetString("APIKEY_읍면동조회", resourceCulture);
            }
        }
    }
}
